@startuml

    interface Declaration {

        kind: string
    }

    interface MemberDeclaration extends Declaration {

        description?: string
    }

    interface PropertyMemberDeclaration extends MemberDeclaration {

        name: string
        private?: boolean
        static?: boolean
    }

    interface MethodMemberDeclaration extends PropertyMemberDeclaration, CallSignatureDeclaration {

        kind: "method"
    }

    interface FieldMemberDeclaration extends PropertyMemberDeclaration {

        kind: "field"
        type?: TypeDeclaration
    }

    interface GetAccessorMemberDeclaration extends PropertyMemberDeclaration {

        kind: "get"
        returns?: TypeDeclaration
    }

    interface SetAccessorMemberDeclaration extends PropertyMemberDeclaration {

        kind: "set"
        parameter: ParameterDeclaration
    }

    interface ConstructorMemberDeclaration extends MemberDeclaration {

        kind: "constructor"
        parameters?: ParameterDeclaration[]
    }

    interface IndexMemberDeclaration extends  MemberDeclaration {

        kind: "index"
        parameter: ParameterDeclaration
        returns: TypeDeclaration
    }
    
@enduml    