@startuml

    interface TypeDeclaration extends Declaration, String {

    }

    interface FunctionTypeDeclaration extends TypeDeclaration, CallSignatureDeclaration {
        kind: "function"
    }

    interface ArrayTypeDeclaration extends TypeDeclaration {

        kind: "array"
        type: TypeDeclaration
    }

    interface ConstructorTypeDeclaration extends TypeDeclaration, CallSignatureDeclaration {

        kind: "constructor"
    }

    interface ObjectTypeDeclaration extends TypeDeclaration {

        kind: "object"
        signatures: SignatureDeclaration[]
    }

    interface TypeReferenceDeclaration extends TypeDeclaration {

        kind: "reference"
        type: string
        arguments: TypeDeclaration[]
    }
    
@enduml